---
title: "행복기숙사 분석 R code"
author: "Junyeon Cho"
date: "`r Sys.Date()`"
output: html_document
---



```{r package, include=FALSE}
library(corrplot)
library(caret)
library(randomForest)
library(tree)
library(dplyr)
library(MVA)
library(car)
library(boot)
library(forecast)
library(DescTools)
library(lmtest)
library(rpart)
```


```{r data load, include=FALSE}
dt<-read.table(file="../dormitory_prediction/기숙사비예측통일데이터.xlsx")
ajouex<-read.csv(file="../dormitory_prediction/아주대데이터.csv")
```


```{r resampling, echo=FALSE}
Q1<-quantile(dt$총기숙사비,0.25)
Q2<-median(dt$총기숙사비)
Q3<-quantile(dt$총기숙사비,0.75)
w1<-which(dt$총기숙사비<Q1)
w2<-which(dt$총기숙사비>=Q1 & dt$총기숙사비<Q2)
w3<-which(dt$총기숙사비>=Q2 & dt$총기숙사비<Q3)
w4<-which(dt$총기숙사비>=Q3)

set.seed(1001)
trnum1001<-sample(29,21)
w1[trnum1001]

set.seed(1002)
trnum1002<-sample(28,21)
w2[trnum1002]

set.seed(1003)
trnum1003<-sample(29,21)
w3[trnum1003]

set.seed(1004)
trnum1004<-sample(29,21)
w4[trnum1004]

trnuman<-c(w1[trnum1001],w2[trnum1002],w3[trnum1003],w4[trnum1004])

trnuman

trnuman[order(trnuman)]
```


```{r datasampling, echo=FALSE}
dttr1 <- dt[trnuman,]
dtts1 <- dt[-trnuman,]
```



```{r}
startmodel<-lm(총기숙사비~1,data=dttr1)
finalmodel<-lm(총기숙사비~재학생수+총.실수+운영된.기간+수용인원.명.+연면적.미터제곱.+재원.공자기금.+재원.주택기금.+재원.자체.+자체재원.비율+실당.인원수+의무식dummy+분교dummy+서울dummy+광역시dummy+경기dummy+학급dummy,data=dttr1)

summary(finalmodel)

stepedmodel<-step(startmodel,direction="both",scope=list(lower=startmodel,upper=finalmodel),trace=0)

stepedmodel$coefficients
```


```{r, echo=FALSE}
summary(stepedmodel)

vif(stepedmodel)

shapiro.test(stepedmodel$residuals)

dwtest(stepedmodel)

ncvTest(stepedmodel)

raintest(stepedmodel)

rstset<-rstudent(stepedmodel)
par(mfrow=c(1,2))
plot(rstset~stepedmodel$fitted.values,main="Studentized Residual vs Fitted",xlab="Fitted Value",ylab="Studentized Residuals",ylim=c(-4,4))
abline(h=c(-3,0,3),lty=c(3,2,3),col=c("red","navy","red"))
fit <- stepedmodel$fitted.values
top3_idx <- order(abs(rstset), decreasing = TRUE)[1:2]
text(fit[top3_idx], rstset[top3_idx], labels = top3_idx, pos = 4)

qqv<-qqnorm(rstset,main="Q-Q Plot of Studentized Residual")
text(qqv$x[top3_idx],qqv$y[top3_idx], labels = top3_idx, pos=c(4,2))
qqline(rstset,col="red")
```






```{r, echo=FALSE}
pdsteped<-predict(stepedmodel,newdata=dtts1,type="response")
Msteps<-mean((dtts1$총기숙사비-pdsteped)^2)
Mateps<-mean(abs(dtts1$총기숙사비-pdsteped))

Msteps
sqrt(Msteps)
Mateps
```



```{r predaa,echo=FALSE}
MSEstpm<-mean((stepedmodel$residuals)^2)
ajstpm<-predict(stepedmodel,newdata=ajouex,type="response")

ajstpm
ajstpm/990

xs<-as.matrix(ajouex[,c(1,4,6,8,10,11,14,21,24)])
Xs<-as.matrix(dttr1[,c(4,8,10,12,14,15,18,25,28)])


PIstps<-c(ajstpm-abs(qt(0.025,74))*sqrt(MSEstpm*(1+1/84+xs%*%solve(t(Xs)%*%Xs)%*%t(xs))),ajstpm+abs(qt(0.025,74))*sqrt(MSEstpm*(1+1/84+xs%*%solve(t(Xs)%*%Xs)%*%t(xs))))

PIstps
PIstps/990

CIstps<-c(ajstpm-abs(qt(0.025,74))*sqrt(MSEstpm*(1/84+xs%*%solve(t(Xs)%*%Xs)%*%t(xs))),ajstpm+abs(qt(0.025,74))*sqrt(MSEstpm*(1/84+xs%*%solve(t(Xs)%*%Xs)%*%t(xs))))

CIstps
CIstps/990
```



